title: Ian Terrell
email: ian.terrell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal homepage of Ian Terrell.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ianterrell.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ianterrell

# Build settings
# theme: minima
# plugins:

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  learn-to-code:
    output: true
    permalink: /books/:collection/:name

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
